config/routes.rb
TripTracker::Application.routes.draw do
  get "welcome/index"
  get 'routes/get_distance'
  post 'routes/get_distance'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'
  get 'logout' => 'sessions#destroy'

  resources :places do
    collection do
      get 'by_name'
      get 'map_distance'
    end
  end

  resources :activity_types

  resources :activities

  resources :users

  resources :trips do
    resources :routes do
      collection do
        get 'cleanup'
      end
    end
  end

  root :to => 'welcome#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :routes, dependent: :destroy
  has_many :major_places, class_name: :Place, conditions: {parent_id: nil}
  has_many :places
  attr_accessible :description, :name, :user_id, :start_date, :end_date
  validates :name, :user_id, presence: true
  validates :name, length: {maximum: 40}
  validates_uniqueness_of :name, scope: :user_id
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :require_login

  def ensure_ownership(trip)
    if trip.user_id != current_user.id
      raise "Trip #{trip.id} does not exist for this user" 
    else
      set_current_trip(trip.id)
    end
  end

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user_id: current_user.id)
    reset_current_trip
    session[:return_to] = request.url

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    ensure_ownership @trip

    @routes = @trip.routes.order('seq_no ASC')
    @first_place_id = @routes.first.nil? ? nil : @routes.first.start_place_id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    reset_current_trip
    @trip = Trip.new
    @trip.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
    ensure_ownership @trip
    @routes = @trip.routes
  end

  # POST /trips
  # POST /trips.json
  def create
    reset_current_trip
    @trip = Trip.new(params[:trip])
    @trip.user_id = current_user.id
    
    respond_to do |format|
      if @trip.save
        format.html { redirect_to places_path(trip_id: @trip.id), notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])
    ensure_ownership @trip

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    reset_current_trip
    @trip = Trip.find(params[:id])
    ensure_ownership @trip
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper

  def get_trip_name(id)
    Trip.find(id).name
  end

  def get_trips
    if get_user
      return Trip.where(user_id: get_user)
    else
      return []
    end
  end
end

app/views/trips/_form.html.erb
<div id="trip_form">
  <%= form_for(@trip) do |f| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

        <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div id="form_left_group">
      <div class="field" id="form_name">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div id="form_start_date">
        Start Date
      </div>
      <div id="form_end_date">
        End Date
      </div>
      <div id="form_flexible">
        Flexibility
      </div>
    </div>
    <div class="field" id="form_description" >
      <%= f.label :description %><br />
      <%= f.text_area :description, rows: "10", cols: "80" %>
    </div>
    <div class="actions">
      <%= f.submit "Save Trip" %>
    </div>
  <% end %>
</div>
  

app/views/trips/edit.html.erb
<h1>Editing trip</h1>
<p>
	<%= link_to "Delete trip", @trip, method: :delete,  data: {confirm: "Are you sure you want to delete this trip?"}%>
</p>
<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<%if get_user && get_trips.count == 0 %>
	You don't have any trips.  Would you like to <%= link_to "Create one?", new_trip_path %>
<% end %>

<div id="show_trips">
  <% @trips.each do |trip| %>
  <div id="show_a_trip">
    <div class="show_a_trip_links">
        <%= link_to  image_tag('/assets/wand.png', title: 'Edit Trip'), edit_trip_path(trip.id) %>
        <%= link_to  image_tag('/assets/builder.png', title: 'Build Trip'), places_path(trip_id: trip.id) %>
        <%= link_to  image_tag('/assets/itinerary.png', title: 'See Itinerary'), trip, trip_id: trip.id %>
    </div>
  	<div class="show_a_trip_name">
  		&nbsp;&nbsp;<%= trip.name %> 
  	</div>

    <ul>
      <li><%= trip.description %></li>
    </ul>
  </div>

<% end %>
</div>

<br />

<%= link_to '[New Trip]', new_trip_path %>
<%= link_to '[Home]', root_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<% total_miles = 0 %>
<% total_cost = 0.0 %>
<% total_activity_cost = 0.0 %>
<% total_gas_cost = 0.0 %>
<table border="0" width="75%">
	<tr>
		<td><h1>Trip <%= @trip.name %> </h1>
			(<%= link_to image_tag('/assets/edit.png'), edit_trip_path(@trip) %> trip)
			(<%= link_to image_tag('/assets/add.png'), new_place_path %> place)
			(<%= link_to image_tag('/assets/add.png'), new_trip_route_path(@trip) %> route)
		</td>
	</tr>
	<tr>
		<td>
			<div id="trip_description">
				<%= @trip.description %> 
			</div>
		</td>
	</tr>

	<% @routes.each do |route| %>
		<tr>
			<td>
				<table border="0" width="100%">
					<col style="width:1%">
					<col style="width:21%">
					<col style="width:78%">
					<tr>
						<td id="route_name" colspan="3">
							<%= route.start_place_name %> to <%= route.end_place_name %><br/>
						</td>
					</tr>
					<tr>
						<td></td>
						<td colspan="2">
							<% if route.distance %>
								<div class="route_distance">
									<%= route.notes %>
									<% 
										total_miles += route.distance; 
										total_cost += route.cost_of_gas + route.cost_of_activities 
										total_gas_cost += route.cost_of_gas 
										total_activity_cost += route.cost_of_activities
									%>
									
									<table>
										<tr>
											<td></td>
											<td class="td_green">Miles</td>
											<td class="td_green">Gas</td>
											<td class="td_green">Activities</td>
											<td class="td_green">Total Cost</td>
										</tr>
										<tr>
											<td class="td_green">Route</td>
											<td class="td_right"><%= route.distance %></td>
											<td class="td_right">$<%= route.cost_of_gas %></td>
											<td class="td_right">$<%= route.cost_of_activities %></td>
											<td class="td_right">$<%= route.cost_of_gas + route.cost_of_activities %></td>
										</tr>
										<tr>
											<td class="td_green">Trip</td>
											<td class="td_right"><%= total_miles %></td>
											<td class="td_right">$<%= total_gas_cost %> </td>
											<td class="td_right">$<%= total_activity_cost %></td>
											<td class="td_right">$<%= total_cost %></td>
										</tr>
									</table>
								</div>
							<% end %>
						</td>
					<tr>
						<td class="place_name" colspan="3">
							<%= route.start_place_name %> 
							<% if route.start_place && route.start_place.arrival_date %>
								on <%= route.start_place.arrival_date %>
							<% end %>
						</td>
					</tr>
					<tr>
						<td></td>
						<td colspan="2">
							<%= link_to image_tag('/assets/add.png'), controller: "activities", action: "new", place_id:@first_place_id  %>
							Activities:
						</td>
					</tr>
					<% if route.start_place %>
						<tr id="start_places" class="show_activities">
							<td colspan="3">
								<ul>
									<% route.start_place.activities.each do |activity| %>
										<li>
											<%= link_to image_tag('/assets/edit.png'), edit_activity_path(activity.id)%>
											<%= activity.show_activity_info %>
										</li>
									<% end %>
								</ul>
								
							</td>
						</tr>	
					<% end %>		
					<% route.start_place.my_minor_places.each do |place| %>	
						<tr>
							<td class="place_name" colspan="3">	<%= place.name %></td>
						</tr>
						<tr>
							<td></td>
							<td colspan="2">
								<%= link_to image_tag('/assets/add.png'), controller: "activities", action: "new", place_id:route.start_place_id  %>
								Activities:
							</td>
						</tr>
						<tr class="show_activities">						
							<td colspan="3">
								<ul>
									<% place.activities.each do |activity| %>
							  			<li>
							  				<%= link_to image_tag('/assets/edit.png'), edit_activity_path(activity.id)%> <%= activity.show_activity_info %>
							  				<% if activity.notes %> - <%= activity.notes %><% end %>
							  			</li>
									<% end %>
								</ul>
							</td>
						</tr>
					<% end %>
		
					<% if route == @routes.last %>
						<tr id="last_place" >
							<td class="place_name" colspan="3">
								<%= route.end_place_name %>
								<% if route.end_place && route.start_place.arrival_date %>
									on <%= route.start_place.arrival_date %>
								<% end %>
							</td>
						</tr>
						<%if route.end_place && @first_place_id != route.end_place_id%>
							<tr class="show_activities">
								<td colspan="3">									
									<ul>
										<% route.end_place.activities.each do |activity| %>
								  			<li>
								  				<%= link_to image_tag('/assets/edit.png'), edit_activity_path(activity.id)%> <%= activity.show_activity_info %>
								  				<% if activity.notes %> - <%= activity.notes %><% end %>
								  			</li>
										<% end %>
									</ul>							
								</td>
							</tr>
						<% end %>
						<tr>
							<td colspan="3">
								<div class="route_distance">
									<p>Stats for this trip:</p>
									<table>
										<tr>
											<td></td>
											<td class="td_green">Miles</td>
											<td class="td_green">Gas</td>
											<td class="td_green">Activities</td>
											<td class="td_green">Total Cost</td>
										</tr>
										<tr>
											<td class="td_green">Trip</td>
											<td class="td_right"><%= total_miles %></td>
											<td class="td_right">$<%= total_gas_cost %> </td>
											<td class="td_right">$<%= total_activity_cost %></td>
											<td class="td_right">$<%= total_cost %></td>
										</tr>
									</table>
								</div>
							</td>
						</tr>
					<% end %>
				</table>
			</td>
		</tr>	
	<% end %>
</table>