config/routes.rb
TripTracker::Application.routes.draw do
  get "welcome/index"
  get 'routes/get_distance'
  post 'routes/get_distance'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'
  get 'logout' => 'sessions#destroy'

  resources :places do
    collection do
      get 'by_name'
      get 'map_distance'
    end
  end

  resources :activity_types

  resources :activities

  resources :users

  resources :trips do
    resources :routes do
      collection do
        get 'cleanup'
      end
    end
  end

  root :to => 'welcome#index'

end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController

  # This controller will either go away or be used only by an admin

  before_filter :require_login
  # GET /activity_types
  # GET /activity_types.json
  def index
    @activity_types = ActivityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_types }
    end
  end

  # GET /activity_types/1
  # GET /activity_types/1.json
  def show
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/new
  # GET /activity_types/new.json
  def new
    @activity_type = ActivityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/1/edit
  def edit
    @activity_type = ActivityType.find(params[:id])
  end

  # POST /activity_types
  # POST /activity_types.json
  def create
    @activity_type = ActivityType.new(params[:activity_type])

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully created.' }
        format.json { render json: @activity_type, status: :created, location: @activity_type }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_types/1
  # PUT /activity_types/1.json
  def update
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      if @activity_type.update_attributes(params[:activity_type])
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.json
  def destroy
    @activity_type = ActivityType.find(params[:id])
    @activity_type.destroy

    respond_to do |format|
      format.html { redirect_to activity_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/activity_types/_form.html.erb
<%= form_for(@activity_type) do |f| %>
  <% if @activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
      <% @activity_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_type %><br />
    <%= f.text_field :activity_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h1>Editing activity_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<h1>Listing activity_types</h1>

<table>
  <tr>
    <th>Activity Type</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activity_types.each do |activity_type| %>
  <tr>
    <td><%= activity_type.activity_type %></td>
    <td><%= activity_type.description %></td>
    <td><%= link_to 'Show', activity_type %></td>
    <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
    <td><%= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<h1>New activity_type</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activity Type:</b>
  <%= @activity_type.activity_type %>
</p>

<p>
  <b>Description:</b>
  <%= @activity_type.description %>
</p>


<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>