config/routes.rb
TripTracker::Application.routes.draw do
  get "welcome/index"
  get 'routes/get_distance'
  post 'routes/get_distance'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'
  get 'logout' => 'sessions#destroy'

  resources :places do
    collection do
      get 'by_name'
      get 'map_distance'
    end
  end

  resources :activity_types

  resources :activities

  resources :users

  resources :trips do
    resources :routes do
      collection do
        get 'cleanup'
      end
    end
  end

  root :to => 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_one :activity_types
  validates :activity_type, :name, presence: true
  validates :cost, numericality: true, :allow_nil => true
  validates :name, uniqueness: true
  attr_accessible :activity_type, :cost, :name, :notes, :place_id
  before_save :set_cost

public

  def set_cost
    if cost.nil?
      self[:cost] = 0
    end
  end
  def self.get_by_id (id)
    Activity.find(id)
  end

  def get_type_name
    ActivityType.find(activity_type).activity_type
  end

  def show_activity_info
    cost_str = cost > 0 ? "for #{cost}" : ""
    "#{name} (#{ActivityType.find(activity_type).activity_type}) #{cost_str}"
  end

  def self.trip_activities(trip_id)
    activities = []
    Place.where(trip_id: trip_id).each do |place|
      Activity.where(place_id: place.id).each do |activity|
        activities << activity
      end
    end
    return activities
  end
end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
  belongs_to :activity
  validates :activity_type, presence: true, uniqueness: true
  attr_accessible :description, :activity_type
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :require_login

  # This controller will go away


  # GET /activities
  # GET /activities.json
  def index
    if session[:trip_id]
      @trip = Trip.find(session[:trip_id])
      @activities = Activity.trip_activities(session[:trip_id])
    else
      @activities = []
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    if params[:place_id]
      @activity.place_id = params[:place_id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }  
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
</p>

   <div class="field">
    <%= f.label :place_id %><br />
    <%= f.collection_select :place_id, Place.where(trip_id: session[:trip_id]) , :id, :name %>
    <!-- <%= f.number_field :place_id %> -->
  </div>

<!-- 
  <div class="field">
    <%= f.label :activity_type %><br />
    <%= f.number_field :activity_type %>
  </div> -->
  
  <div class="field">
    <%= f.label :activity_type %><br />
    <%= f.collection_select :activity_type, ActivityType.find(:all, order: "activity_type"), :id, :activity_type %>
  </div>

  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Activity type</th>
    <th>Place</th>
    <th>Cost</th>
    <th>Notes</th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td>
      <%= link_to image_tag('/assets/wand.png'), edit_activity_path(activity) %>
      <%= link_to image_tag('/assets/trash.png'),  activity, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    <td>
      <% if activity.place_id %>
        <%= link_to activity.name , activity %>
      <% else %>
            No place assigned
      <% end %>
    </td>
    <td><%= ActivityType.find(activity.activity_type).activity_type %></td>
    <td>
      <% if activity.place_id %>
        <%= Place.find(activity.place_id).name %> 
      <% else %>
        No place assigned
      <% end %>
    </td>
    <td><%= activity.cost %></td>
    <td><%= activity.notes %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>


<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p>
  <b>Activity type:</b>
  <%= @activity.activity_type %>
</p>

<p>
  <b>Cost:</b>
  <%= @activity.cost %>
</p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @activity.notes %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>