config/routes.rb
TripTracker::Application.routes.draw do
  get "welcome/index"
  get 'routes/get_distance'
  post 'routes/get_distance'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'
  get 'logout' => 'sessions#destroy'

  resources :places do
    collection do
      get 'by_name'
      get 'map_distance'
    end
  end

  resources :activity_types

  resources :activities

  resources :users

  resources :trips do
    resources :routes do
      collection do
        get 'cleanup'
      end
    end
  end

  root :to => 'welcome#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  include PlacesHelper
  include ActionView::Helpers::TextHelper

  attr_accessible :name, :notes, :trip_id, :arrival_date, :days, :after_id, :active, :parent_id, :seq_no

  has_many :activities, dependent: :destroy
  belongs_to :trip

  validates :name, :trip_id, presence: true
  validates_uniqueness_of :name, scope: [:trip_id]

  before_save     :fix_seq_no, :update_my_minor_places_status
  after_save      :fix_routes
  before_destroy  :delete_my_minor_places                       # minor places depend on their parent
  after_destroy   :fix_seq_no_after_destroy, :fix_routes        # removing a place may affect the other of others, and the routes

  public 

  # minor places in between start and end
  def my_minor_places
    return Place.where(trip_id: self.trip_id, parent_id: self.id)
  end

  # cost only at this place/destination
  def cost_of_activities
    Activity.where(place_id: id).each.inject(0) {|sum, activity| sum + activity.cost}
  end

  # this includes this and all minor places that follow it
  def cost_of_activities_at_destination
    total_cost=cost_of_activities # cost at this location
    my_minor_places.each do |place|
      total_cost += place.cost_of_activities
    end
  end

  def self.remove_trip_inactive_places(trip_id)
    trip = Trip.find(trip_id)
    trip.places.where(active: false).each do |place|
      place.destroy
    end
  end

    def showArrivalDate
    if arrival_date
      arrival_date.strftime("%b %-d")
    end 
  end

  def showDuration
    if days
      pluralize(days, "day")
    end
  end

  protected

  def fix_seq_no
    PlaceOrderManager.new.account_for(self)
  end

  def fix_seq_no_after_destroy
    PlaceOrderManager.new.update_places(self)
  end

  def delete_my_minor_places
    my_minor_places.each do |minor_place| 
      minor_place.destroy
    end
  end

  def update_my_minor_places_status
    if self.active_changed?
      my_minor_places.each do |minor_place| 
        minor_place.update_attributes(active: self.active) if (minor_place.active != self.active)
      end
    end
  end

  def fix_routes
    Route.fix_routes(trip_id)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :require_login
  before_filter :set_trip_params

  def proper_ownership?(place=nil)
    if !current_trip?
      flash[:notice] = "Places can only be managed withing the context of a particular trip."
      return false
    end
    if place && place.trip_id != current_trip.id
        flash[:notice] = "This place does not belong to the current trip."
        return false
    end
    return true
  end

  # useful when selecting a trip from list of trip, so we can build it 
  def set_trip_params
    if  params[:trip_id]
      trip_id = params[:trip_id]
      set_current_trip(trip_id)
    else
      trip_id = session[:trip_id]
    end
    #Rails.logger.debug "set_trip_params id: #{trip_id} or #{params[:trip_id]} and name: #{params[:place][:name]}"
    @trip = Trip.find(trip_id)
  end

  def get_places_select(parent_id)
   if parent_id
      parent = Place.find(parent_id)
      places_select = [parent]
    else
      places_select = @trip.major_places.order('seq_no ASC').all
    end
    return places_select
  end

  # GET /places
  # GET /places.json
  def index
    unless proper_ownership?
      redirect_to welcome_index_path
      return
    end
    @trip = current_trip
    session[:return_to] = request.url
    @major_places = @trip.major_places.order('seq_no ASC')
    @routes = @trip.routes.order('seq_no ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    unless proper_ownership? @place
      redirect_to welcome_index_path
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    Rails.logger.debug "Beginning of new"
    unless proper_ownership?
      redirect_to welcome_index_path
      return
    end
    @place = Place.new
    @trip = current_trip
    if params[:prev_place]
      @prev_place = Place.find(params[:prev_place])
      unless proper_ownership? @prev_place
        redirect_to welcome_index_path
        return
      end
    end
    @parent_id = params[:parent_id]
    @places_select = get_places_select(@parent_id)

    respond_to do |format|
      format.html # { new.html.erb}
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    session[:return_to] = request.referer
    @place = Place.find(params[:id])
    if params[:prev_place]
      @prev_place = Place.find(params[:prev_place])   # this is set for all BUT the first place
      unless proper_ownership? @prev_place
        redirect_to welcome_index_path
        return
      end
    end
    @trip = Trip.find(@place.trip_id)
    @parent_id = params[:parent_id]
    @places_select = get_places_select(@parent_id)
    unless proper_ownership? @place
      redirect_to welcome_index_path
      return
    end
  end

  # POST /places
  # POST /places.json
  def create
    @trip = current_trip
    @place = Place.new(params[:place])
    @parent_id = params[:parent_id]
    @places_select = get_places_select(@parent_id)
    unless proper_ownership? @place
      redirect_to welcome_index_path
      return
    end
   
    respond_to do |format|
      if @place.save
        format.html { redirect_to places_path, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  #PUT /places/1
  #PUT /places/1.json
  def update
    @place = Place.find(params[:id])
    @parent_id = params[:parent_id]
    @places_select = get_places_select(@parent_id)
    unless proper_ownership? @place
      redirect_to welcome_index_path
      return
    end
    @trips = [current_trip]

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to session[:return_to], notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to session[:return_to] }
      format.json { head :no_content }
    end
  end

  def by_name
    @places_match=Array.new
    if params[:name].empty?
      return @places_match
    end
    
    Place.all.each do |place|
      place_pat = Regexp.compile(params[:name])  
      if place_pat =~ place.name
        @places_match << place
      end
    end
  end

  def map_distance
  end
end

app/helpers/places_helper.rb
module PlacesHelper

 #is this the first place created or the one with smallest seq_no?
  def first_place?(trip, place)
    trip.major_places.count == 0 or (place && place.seq_no == 1)
  end

  def default_arrival_date(prev_place)
    if prev_place && prev_place.days && prev_place.arrival_date
      desired_date=prev_place.arrival_date.next_day(prev_place.days)
    elsif prev_place && prev_place.arrival_date
      desired_date=prev_place.arrival_date
    end
    return {year: desired_date.year, month: desired_date.month, day: desired_date.day} if desired_date
  end

  # manage seq_no for places both globally and for minor place (which are grouped under a major place)
  class PlaceOrderManager
    def account_for(place)
      if !place.id && !place.seq_no                     # new place, didn't specify position: put it at the end
          place.seq_no = get_max_seq_no(place)+1          
      elsif !place.id && place.seq_no                   # new place, specified position: insert at that location
        insert_place(place)
      else                                              # existing place: if seq_no has changed, move it to new location
        existing_place = Place.find(place.id)
        if existing_place.seq_no != place.seq_no
          @places_ref ||= get_places(place)
          move_place(existing_place.seq_no, place)
        end
      end
    end

    # this gets called when you want to insert a place before others
    # this will also be called after a place is removed, to fix the seq_no of the rest
    def update_places(place)
      @places_ref ||= get_places(place)
      Rails.logger.debug "in update_place: ref: #{@places_ref.inspect}"
      @places_ref.each_with_index do |place, index|
        if place[:id]                                    # if this is null it's for a new place which is already in the right order
          db_place = Place.find(place[:id])
          if (index) != db_place.seq_no-1
            db_place.update_column(:seq_no, index+1)
          end
        end
      end
    end

    private
    def get_places(place)
      if place.parent_id
        @places_ref ||= Place.find(place.parent_id).my_minor_places.map {|p| make_places_ref(p)}
      else
        @places_ref ||= Place.where(trip_id: place.trip_id).order('seq_no ASC').map {|p|make_places_ref(p)}
      end
    end

    def make_places_ref(place)                  # only keep track of essential fields
      {id: place.id, seq_no: place.seq_no}
    end
  
    def get_max_seq_no(place)
      if place.parent_id
        Place.where(trip_id: place.trip_id, parent_id: place.parent_id).count
      else
        Place.where(trip_id: place.trip_id, parent_id: nil).count
      end
    end

    def fix_place_seq_no(place, adding_place)
      Rails.logger.debug "place: #{place.inspect} new is #{adding_place}"
      max_seq_no = get_max_seq_no(place)
      if adding_place
        max_seq_no +=1
      end      
      new_seq_no = place.seq_no > max_seq_no ? max_seq_no : place.seq_no 
      if place.seq_no != new_seq_no
          Rails.logger.debug "User attempted to set to_index to #{place.seq_no}, which is larger than max value of #{max_seq_no}"
          place.seq_no = new_seq_no
      end
      Rails.logger.debug "new_seq_no: #{new_seq_no}"
      return new_seq_no
    end

    def insert_place(place)
      fix_place_seq_no(place, true)
      get_places(place).insert(place.seq_no-1, make_places_ref(place))
      update_places(place)
    end

    def move_place(from_index, place)
      fix_place_seq_no(place, false)
      places_ref = get_places(place)
      p_ref = places_ref.delete_at(from_index-1)
      places_ref.insert(place.seq_no-1, p_ref)
      update_places(place)
    end
  end
end

app/views/places/_build_places.html.erb
<div id="edit_parts">
	<div id="places_part" class="inline_block">
		<h2>Your places</h2>
		Use this section to add, move, or delete places on your trip.
		<table>
			<% @major_places.each do |place| %>
				<tr>
					<td class="seq_no"> <%= place.seq_no  %></td>

					<td class="place_part"><%= place.name %></td>
					<td ><%= place.showArrivalDate %></td>
					<td><%= place.showDuration %></td>
					<td id="buttons">
						<%= link_to image_tag('/assets/wand.png', title: 'edit place'), edit_place_path(place.id, prev_place: @save_place_id) %>
						<%= link_to image_tag('/assets/trash.png', title: 'delete place'), place, method: :delete,  data: {confirm: "Are you sure you want to delete this place?"} %>
						<%= link_to image_tag('/assets/plus.png', title: 'add place below'), new_place_path(prev_place: place.id) %>				
					</td>
				</tr>
				<% @save_place_id = place.id %>
				<% place.my_minor_places.each do |minor_place| %>
					<tr>
						<td class="seq_no"> <%= minor_place.seq_no  %></td>
						<td class="minor_place_part"><%= minor_place.name %></td>
						<td><%= minor_place.showArrivalDate %></td>
						<td><%= minor_place.showDuration %></td>
						<td id="buttons">
							<%= link_to image_tag('/assets/wand.png', title: 'edit place'), edit_place_path(minor_place.id, parent_id:place.id) %>	
							<%= link_to image_tag('/assets/trash.png', title: 'delete place'), minor_place, method: :delete,  data: {confirm: "Are you sure you want to delete this place?"} %>						
							<%= link_to image_tag('/assets/plus.png', title: 'add place below'), new_place_path(parent_id: place.id) %>
						</td>
					</tr>
				<% end %>
					<tr>		
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td class="minor_place_part", id="buttons">
							<%= link_to image_tag('/assets/plus.png', title: 'add place below'), new_place_path(parent_id: place.id) %>
						</td>
					</tr>
			<% end %>
		</table>
		<div id="after_edit_parts">
			<% if @major_places.count == 0 %>
				<p>
					Where do you want to go?
				</p>
				<%= link_to "Create your first destination".html_safe, new_place_path  %>
			<% else %>
			<p>
				<%= link_to "Add place", new_place_path(prev_place: @save_place_id) %>
			</p>
			<% end %>
		</div>
		<div id="place_spacer">			
		</div>
	</div>
	 <%= render 'routes/route_list' %>
</div>




<div id="spacer"></div>

app/views/places/_form.html.erb
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&key=AIzaSyD7dX6kGdaqlOai_k7__h6tr-2MR9goD6o" %>
<%= javascript_include_tag "find_place" %>
          
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if @last_place %>
    <%= f.hidden_field :last_place, value: @last_place %>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br />
    <%= f.collection_select :trip_id, [ @trip ], :id, :name %>
  </div>

  <% if @parent_id %>
    <div class="field">
      <%= f.label :destinations %><br />
      <%= f.collection_select :parent_id, @places_select, :id, :name %>
    </div>
  <% else %>
    <div class="field">
        <p>
          If you want this place to be saved as an excursion under an existing destination (as a daytrip, for example), select that place from the list.
        </p>
        <%= f.label 'Under destination name' %><br />
        <%= f.collection_select :parent_id, @places_select, :id, :name, include_blank: 'None' %>
    </div>
  <% end %>

  <div class="field" id="panel" style="margin-left: 0px">
    <%= f.label :name %><br />
    <%= f.text_field :name, id: "searchTextField", size: "50", autofocus: true %>
  </div>
  <div id="map-canvas"></div>


  <% if first_place?(@trip, @place) %>
    <div class="field">
      <%= f.label 'Start Date' %><br />
      <%= f.date_select :arrival_date, :start_year => 2013, :prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' } %>
    </div>

  <% else %>
    <div class="field">
      <%= f.label :arrival_date %><br />
      <%= f.date_select :arrival_date, :start_year => 2013, :default => default_arrival_date(@prev_place) %>
   </div>

    <div class="field">
      <%= f.label :days, "Nights" %><br />
      <%= f.text_field :days %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seq_no %><br />
    <%= f.text_field :seq_no %>
  </div>

  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_places.html.erb
<% @places.each do |place| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %> ">
    <td>
      <%= link_to image_tag('/assets/edit.png'), edit_place_path(place) %>
      <%= link_to image_tag('/assets/delete.png'),  place, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    <td><%= link_to place.name, place %></td>
    <td>
    </td>
    <td><%= place.notes %></td>
  </tr>
<% end %>

app/views/places/add_activity.html.erb
<% render new_activity_path, place_id: params[:id] %>

app/views/places/by_name.html.erb
<p>
	
	Looking for places matching "<%= params[:name] %>"
<table border="1">
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Notes</th>
	</tr>
	<tr>
	<% @places_match.each do |pl| %>
		<td> <%= pl.id %></td>
		<td> <%= pl.name %></td>
		<td><%= pl.notes %></td>
	<% end %>
	</tr> 
</table>
</p>

<p>
	Controller/action: <%= params[:controller] %>/<%= params[:action] %>
</p>
<p>
	Go <%= link_to "Home", root_path %>.
</p>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1> Build your trip</h1>

 <%= render 'build_places' %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>


<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p>
  <b>Trip:</b>
  <%= Trip.find(@place.trip_id).name %>
</p>

<p>
  <b>Name:</b>
  <%= @place.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @place.notes %>
</p>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>